#SPDX-License-Identifier: MIT-0
---
# defaults file for ansible/roles/database
dockerhub_username: grimortel
database_image: "{{ dockerhub_username }}/tp-devops-database:latest"
db_container_name: postgres-db
db_name: db
db_user: usr
db_password: pwd
docker_network_name: app_network
