# Récupérer l'image d'Apache 
FROM httpd:2.4

# Copier mon fichier dans Apache
COPY index.html /usr/local/apache2/htdocs/index.html

# Copier la configuration Apache personnalisée
COPY httpd.conf /usr/local/apache2/conf/httpd.conf